# Pandas
Welcome to the fifth lesson! This Jupyter Notebook file is meant to accompany **L05 - Pandas.**

Type your solutions for each exercise in the code cells below, and then press **Shift + Enter** to execute your code. Then, check the solution video to see how you did!

In [1]:
import pandas as pd

### 1. Introduction to Pandas

In [3]:
manual_dataframe = pd.DataFrame({
    'Current_Price': [223.84, 1970.19, 113.37],
    'Name': ['Apple', 'Amazon', 'Microsoft'],
    'Ticker': ['AAPL', 'AMZN', 'MSFT'],
})
manual_dataframe

   Current_Price       Name Ticker
0         223.84      Apple   AAPL
1        1970.19     Amazon   AMZN
2         113.37  Microsoft   MSFT

In [6]:
excel_dataframe = pd.read_excel('data/excel_stocks.xlsx')
excel_dataframe

   Current_Price       Name Ticker
0         223.84      Apple   AAPL
1        1970.19     Amazon   AZMN
2         113.37  Microsoft   MSFT

In [7]:
excel_dataframe.head(2)

   Current_Price    Name Ticker
0         223.84   Apple   AAPL
1        1970.19  Amazon   AZMN

In [8]:
excel_dataframe.tail(2)

   Current_Price       Name Ticker
1        1970.19     Amazon   AZMN
2         113.37  Microsoft   MSFT

In [9]:
excel_dataframe.shape

(3, 3)

### 2. New Object Type: Pandas DataFrames

<font color = 'blue'> **EXERCISE 2.1** </font>

![instructions](figures/exercise_2_1_instructions.png)

In [10]:
stock_data = pd.read_csv('data/stock_data.csv')
stock_data.shape

(100, 7)

In [11]:
stock_data.head(3)

,Ticker,Name,Sector,Beta,Market Cap,Current Price,Price Target
0,AAPL,APPLE INC,Information Technology,1.09,1081130615,223.84,232.27
1,AMZN,AMAZON.COM INC,Consumer Discretionary,1.23,960942834,1970.19,2133.39
2,MSFT,MICROSOFT CORP,Information Technology,1.46,869345788,113.37,122.30

In [12]:
stock_data.tail(3)

,Ticker,Name,Sector,Beta,Market Cap,Current Price,Price Target
97,ADP,AUTOMATIC DATA,Information Technology,0.96,64599683,147.46,145.73
98,MOLZ,MONDELEZ INTER-A,Consumer Staples,0.74,64235373,43.80,49.20
99,AGN,ALLERGAN PLC,Health Care,1.01,63890227,188.22,211.68

<font color = 'blue'> **EXERCISE 2.2** </font>

![instructions](figures/exercise_2_2_instructions.png)

In [17]:
print(stock_data.select_dtypes(include='number').min())
print('---')
print(stock_data.select_dtypes(include='number').max())

Beta                    0.22
Market Cap       63890227.00
Current Price          12.68
Price Target           15.56
dtype: float64
---
Beta             1.840000e+00
Market Cap       1.081131e+09
Current Price    3.249990e+05
Price Target     3.571250e+05
dtype: float64

In [15]:
print(stock_data.describe())

             Beta    Market Cap  Current Price   Price Target
count  100.000000  1.000000e+02     100.000000      93.000000
mean     0.995800  1.756136e+08    3441.165500    4051.011720
std      0.283446  1.806083e+08   32481.881894   37011.566893
min      0.220000  6.389023e+07      12.680000      15.560000
25%      0.810000  8.195384e+07      69.630000      74.530000
50%      0.990000  1.119556e+08     117.600000     123.930000
75%      1.182500  1.987309e+08     219.430000     217.130000
max      1.840000  1.081131e+09  324999.000000  357125.000000

### 3. New Object Type: Pandas Series

<font color = 'blue'> **EXERCISE 3.1** </font>

### 4. Filtering Data with Boolean Masks

<font color = 'blue'> **EXERCISE 4.1** </font>

### 5. Segmenting Data with Groupby

<font color = 'blue'> **EXERCISE 5.1** </font>