# Pandas
Welcome to the fifth lesson! This Jupyter Notebook file is meant to accompany **L05 - Pandas.**

Type your solutions for each exercise in the code cells below, and then press **Shift + Enter** to execute your code. Then, check the solution video to see how you did!

In [17]:
# import modules
import numpy as np
import pandas as pd

### 1. Introduction to Pandas

In [18]:
# Playground

# create DataFrame
manual_df = pd.DataFrame({
    'Current Price' : [ 223.84, 1970.19, 113.37],
    'Name' : ['Apple', 'Amazon', 'Microsoft'],
    'Ticker':['AAPL', 'AMZN', 'MSFT']
})

manual_df

   Current Price       Name Ticker
0         223.84      Apple   AAPL
1        1970.19     Amazon   AMZN
2         113.37  Microsoft   MSFT

### 2. New Object Type: Pandas DataFrames

<font color = 'blue'> **EXERCISE 2.1** </font>

## Exercise 2.1 Instructions
1. Import pandas as pd if not already done
2. Import stock_data.csv into a new dataframe named stock_data
3. Display the dimensions
4. In a new cell, display the first 3 rows
5. In a new cell, display the last 3 rows

In [19]:
# import stock data
stock_data = pd.read_csv('../../data/raw/stock_data.csv')
stock_data.shape

(100, 7)

In [20]:
# Display the first 3 rows
stock_data.head(3)

,Ticker,Name,Sector,Beta,Market Cap,Current Price,Price Target
0,AAPL,APPLE INC,Information Technology,1.09,1081130615,223.84,232.27
1,AMZN,AMAZON.COM INC,Consumer Discretionary,1.23,960942834,1970.19,2133.39
2,MSFT,MICROSOFT CORP,Information Technology,1.46,869345788,113.37,122.30

In [21]:
# Display the last 3 rows
stock_data.tail(3)

,Ticker,Name,Sector,Beta,Market Cap,Current Price,Price Target
97,ADP,AUTOMATIC DATA,Information Technology,0.96,64599683,147.46,145.73
98,MOLZ,MONDELEZ INTER-A,Consumer Staples,0.74,64235373,43.80,49.20
99,AGN,ALLERGAN PLC,Health Care,1.01,63890227,188.22,211.68

<font color = 'blue'> **EXERCISE 2.2** </font>

## Exercise 2.2 Instructions
1. Print the minimum values of all columns in stock_data
2. Print the maximum values of all columns in stock_data
3. In a new cell, display all numerical summary statistics for stock_data

In [22]:
# Print info
stock_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Ticker         100 non-null    object
 1   Name           100 non-null    object
 2   Sector         93 non-null     object
 3   Beta           100 non-null    float64
 4   Market Cap     100 non-null    int64
 5   Current Price  100 non-null    float64
 6   Price Target   93 non-null     float64
dtypes: float64(3), int64(1), object(3)
memory usage: 5.6+ KB

In [23]:
# max price of Current Price column
np.max(stock_data['Current Price'])

np.float64(324999.0)

In [24]:
stock_data.dtypes

Ticker            object
Name              object
Sector            object
Beta             float64
Market Cap         int64
Current Price    float64
Price Target     float64
dtype: object

In [25]:
stock_data['Sector'].unique()

array(['Information Technology', 'Consumer Discretionary', 'Financials',
       'Health Care', 'Energy', 'Consumer Staples', nan,
       'Telecommunication Services', 'Industrials',
       'Information Technology .', 'Materials', 'Industrial$',
       'Utilities', 'Enersy', 'lndustrials', 'Real Estate'], dtype=object)

In [26]:
stock_data.max(numeric_only=True)

Beta             1.840000e+00
Market Cap       1.081131e+09
Current Price    3.249990e+05
Price Target     3.571250e+05
dtype: float64

In [27]:
# min values
stock_data.min(numeric_only=True) # If dtypes shows other than numeric values, python does not know how to evaluate.

Beta                    0.22
Market Cap       63890227.00
Current Price          12.68
Price Target           15.56
dtype: float64

In [28]:
stock_data.describe()

             Beta    Market Cap  Current Price   Price Target
count  100.000000  1.000000e+02     100.000000      93.000000
mean     0.995800  1.756136e+08    3441.165500    4051.011720
std      0.283446  1.806083e+08   32481.881894   37011.566893
min      0.220000  6.389023e+07      12.680000      15.560000
25%      0.810000  8.195384e+07      69.630000      74.530000
50%      0.990000  1.119556e+08     117.600000     123.930000
75%      1.182500  1.987309e+08     219.430000     217.130000
max      1.840000  1.081131e+09  324999.000000  357125.000000

### 3. New Object Type: Pandas Series

<font color = 'blue'> **EXERCISE 3.1** </font>

![Exercise 3.1](images/ex_3_1.png)

In [29]:
# Display first row of data
print(stock_data.head(1))

# Create new features
stock_data['Price Increase'] = stock_data['Price Target'] - stock_data['Current Price']
stock_data['Return'] = stock_data['Price Increase'] / stock_data['Current Price']
stock_data.head(1)

  Ticker       Name                  Sector  Beta  Market Cap  Current Price  \
0   AAPL  APPLE INC  Information Technology  1.09  1081130615         223.84

   Price Target
0        232.27

,Ticker,Name,Sector,Beta,Market Cap,Current Price,Price Target,Price Increase,Return
0,AAPL,APPLE INC,Information Technology,1.09,1081130615,223.84,232.27,8.43,0.037661

In [30]:
# Summary Stats for Return
stock_data['Return'].describe()

count    93.000000
mean      0.093774
std       0.073729
min      -0.046877
25%       0.034946
50%       0.078769
75%       0.148719
max       0.270456
Name: Return, dtype: float64

### 4. Filtering Data with Boolean Masks

<font color = 'blue'> **EXERCISE 4.1** </font>

![Exercise 4.1](images/ex_4_1.png)

In [31]:
# display first 3 rows of stock data
stock_data.head(3)

,Ticker,Name,Sector,Beta,Market Cap,Current Price,Price Target,Price Increase,Return
0,AAPL,APPLE INC,Information Technology,1.09,1081130615,223.84,232.27,8.43,0.037661
1,AMZN,AMAZON.COM INC,Consumer Discretionary,1.23,960942834,1970.19,2133.39,163.20,0.082835
2,MSFT,MICROSOFT CORP,Information Technology,1.46,869345788,113.37,122.30,8.93,0.078769

In [32]:
# create a boolean mask for Information Technology companies

is_info_tech = (stock_data['Sector'] == 'Information Technology').astype(int)
stock_data['is_IT'] = is_info_tech
stock_data.head(3)

,Ticker,Name,Sector,Beta,Market Cap,Current Price,Price Target,Price Increase,Return,is_IT
0,AAPL,APPLE INC,Information Technology,1.09,1081130615,223.84,232.27,8.43,0.037661,1
1,AMZN,AMAZON.COM INC,Consumer Discretionary,1.23,960942834,1970.19,2133.39,163.20,0.082835,0
2,MSFT,MICROSOFT CORP,Information Technology,1.46,869345788,113.37,122.30,8.93,0.078769,1

### 5. Segmenting Data with Groupby

<font color = 'blue'> **EXERCISE 5.1** </font>

## Exercise 5.1 Instructions
- Calculate the mean for all features by industry sector

In [34]:
stock_data.groupby('Sector').mean(numeric_only=True)

,Beta,Market Cap,Current Price,Price Target,Price Increase,Return,is_IT
Sector,,,,,,,
Consumer Discretionary,0.907692,1.875567e+08,422.383846,468.329231,45.945385,0.086719,0.0
Consumer Staples,0.675000,1.392211e+08,88.859000,94.648000,5.789000,0.079098,0.0
Energy,0.910000,1.865371e+08,83.757500,97.650000,13.892500,0.164425,0.0
Enersy,0.860000,6.824144e+07,117.820000,140.690000,22.870000,0.194110,0.0
Financials,1.155000,1.856177e+08,27198.074167,29894.575833,2696.501667,0.137083,0.0
Health Care,0.954211,1.275709e+08,177.760000,186.905789,9.145789,0.056757,0.0
Industrial$,1.190000,1.219452e+08,207.880000,217.130000,9.250000,0.044497,0.0
Industrials,1.032500,1.189380e+08,179.236250,198.453750,19.217500,0.112912,0.0
Information Technology,1.224444,2.958042e+08,199.093889,222.621667,23.527778,0.096953,1.0
Information Technology .,1.840000,1.680694e+08,276.430000,286.090000,9.660000,0.034946,0.0
Materials,1.360000,1.582399e+08,68.580000,81.260000,12.680000,0.184894,0.0
Real Estate,0.460000,6.488651e+07,147.190000,160.680000,13.490000,0.091650,0.0
Telecommunication Services,0.665000,2.347001e+08,44.075000,46.020000,1.945000,0.048400,0.0
Utilities,0.220000,8.189415e+07,173.650000,176.720000,3.070000,0.017679,0.0
lndustrials,1.120000,6.754730e+07,255.440000,283.180000,27.740000,0.108597,0.0

In [38]:
stock_data.groupby('Sector')['Return'].mean() # just the mean of the series `Return` using groupby

Sector
Consumer Discretionary        0.086719
Consumer Staples              0.079098
Energy                        0.164425
Enersy                        0.194110
Financials                    0.137083
Health Care                   0.056757
Industrial$                   0.044497
Industrials                   0.112912
Information Technology        0.096953
Information Technology .      0.034946
Materials                     0.184894
Real Estate                   0.091650
Telecommunication Services    0.048400
Utilities                     0.017679
lndustrials                   0.108597
Name: Return, dtype: float64