# Liquidity Predictor
Welcome to the eighth lesson! This Jupyter Notebook file is meant to accompany **L08 - Liquidity Predictor.**

Type your solutions for each exercise in the code cells below, and then press **Shift + Enter** to execute your code. Then, check the solution video to see how you did!

### 1. Liquidity Predictor Introduction

In [6]:
import pandas as pd
df_client = pd.read_csv('../data/raw/liquidity_client.csv')

In [7]:
df_client.head(3)

,sp_score,market_cap,total_debt,ltm_capex,ltm_ebitda,ltm_fcf,ltm_revenue
0,2,54856.1961,84628,-9262,21387.00032,9488,170315

### 2. Data Exploration

![Exercise 2.1](../figures/exercise_2_1.png)

<font color = 'blue'> **EXERCISE 2.1** </font>

In [23]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso, Ridge, ElasticNet
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [4]:
df_liquidity = pd.read_csv('../data/raw/liquidity_data.csv')
df_liquidity.head(3)

,available_liquidity,sp_score,market_cap,total_debt,ltm_capex,ltm_ebitda,ltm_fcf,ltm_revenue
0,28694.04271,2,54856.1961,84628.0,-9262.0,21387.00032,9488.0,170315.0
1,24784.00051,7,209150.6401,57909.0,-2021.0,15161.00019,12105.0,37727.0
2,24142.00013,6,180108.3453,32970.0,-1817.0,15818.99981,12604.0,192592.0

In [8]:
df_liquidity.shape

(802, 8)

<font color = 'blue'> **EXERCISE 2.2** </font>

![Exercise 2.2](../figures/exercise_2_2.png)

![liquidity metadata descriptions](../figures/liquidity_metadata.png)

In [5]:
df_liquidity.describe()

,available_liquidity,sp_score,market_cap,total_debt,ltm_capex,ltm_ebitda,ltm_fcf,ltm_revenue
count,802.000000,802.000000,802.000000,802.000000,802.00000,802.000000,802.000000,802.000000
mean,3884.952199,3.017456,41645.089870,9040.720589,-1200.91799,3455.752891,1772.335973,20420.383638
std,4267.893247,1.851461,74046.522440,12112.161513,2066.29159,5679.466199,4207.345101,39483.422972
min,267.000000,0.000000,4282.810112,0.000000,-15858.00000,-6530.000000,-4888.000000,503.586000
25%,1288.328992,2.000000,10082.091010,2125.297000,-1241.00000,936.200000,232.923000,3791.525000
50%,2395.700000,3.000000,19349.403650,4562.000000,-512.00000,1695.700032,682.110000,8587.166000
75%,4512.458596,4.000000,41154.826240,10478.000000,-190.00000,3706.000000,1788.000000,18816.000000
max,28694.042710,10.000000,777070.706700,87032.000000,-5.04900,69715.000320,53244.000000,487511.000000

### 3. Splitting Data

**Lesson Workspace**

In [10]:
# Import train_test_split() from Scikit Learn's model_selection module

#  This was performed at the beginning of the notebook.  I like to keep all the imports at the top.

<font color = 'blue'> **EXERCISE 3.1** </font>

![Exercise 3.1](../figures/exercise_3_1.png)

![drop.png: explanation of using the drop command](../figures/drop.png)

In [11]:
# Define a Series named "target" containing only the target variable
target = df_liquidity.available_liquidity

# Define a DataFrame named "inputs" containing only the input features
inputs = df_liquidity.drop(columns=['available_liquidity'])

In [12]:
# Display the first row of target
target.head(1)

0    28694.04271
Name: available_liquidity, dtype: float64

In [13]:
# Display the first row of inputs
inputs.head(1)

,sp_score,market_cap,total_debt,ltm_capex,ltm_ebitda,ltm_fcf,ltm_revenue
0,2,54856.1961,84628.0,-9262.0,21387.00032,9488.0,170315.0

**Lesson Workspace**

In [14]:
# Split your data and pass the results to a new object named "results"
results = train_test_split(inputs, target, test_size=0.2, random_state=1)

In [16]:
# Print the type() and len() of results
print(type(results))
print(len(results))
print('---')

# For each item in results, print the item's dimensions
for item in results:
    print(item.shape)

<class 'list'>
4
---
(641, 7)
(161, 7)
(641,)
(161,)

<font color = 'blue'> **EXERCISE 3.2** </font>

![exercise 3.2](../figures/exercise_3_2.png)

In [17]:
# Assign the results to the following variables: input_train, input_test, target_train, target_test

input_train, input_test, target_train, target_test = results

**Lesson Workspace**

In [18]:
input_train.head(1)

,sp_score,market_cap,total_debt,ltm_capex,ltm_ebitda,ltm_fcf,ltm_revenue
309,3,16764.94643,1887.019,-483.002,1905.83296,859.71,8653.205

In [19]:
input_test.head(1)

,sp_score,market_cap,total_debt,ltm_capex,ltm_ebitda,ltm_fcf,ltm_revenue
8,8,172479.4798,24842.0,-1674.0,10841.00006,6830.0,39929.0

In [20]:
target_train.head(1)

309    1227.539
Name: available_liquidity, dtype: float64

In [21]:
target_test.head(1)

8    17708.00026
Name: available_liquidity, dtype: float64

### 4. Model Pipelines

**Lesson Workspace**

In [24]:
# Import required functions from Scikit-Learn
# The libraries were imported at the beginning of the notebook.

# Create pipelines dictionary with model pipelines for Lasso and Ridge
pipelines = {
    'lasso' : make_pipeline(StandardScaler(), Lasso(random_state=1)),
    'ridge' : make_pipeline(StandardScaler(), Ridge(random_state=1)),
}

In [25]:
# Add pipeline for Elastic Net
# Dict_name['key'] = value

pipelines['enet'] = make_pipeline(StandardScaler(), ElasticNet(random_state=1))

In [26]:
pipelines

{'lasso': Pipeline(steps=[('standardscaler', StandardScaler()),
                 ('lasso', Lasso(random_state=1))]),
 'ridge': Pipeline(steps=[('standardscaler', StandardScaler()),
                 ('ridge', Ridge(random_state=1))]),
 'enet': Pipeline(steps=[('standardscaler', StandardScaler()),
                 ('elasticnet', ElasticNet(random_state=1))])}

<font color = 'blue'> **EXERCISE 4.1** </font>

**Lesson Workspace**

In [ ]:
# Run this cell to verify that all 5 pipelines are properly defined
for key, value in pipelines.items():
    print(key, type(value))

### 5. Hyperparameter Tuning

**Lesson Workspace**

In [ ]:
# Create a hyperparameter grid for Lasso

<font color = 'blue'> **EXERCISE 5.1** </font>

In [ ]:
# Create a hyperparameter grid for Ridge


# Create a hyperparameter grid for Elastic Net

<font color = 'blue'> **EXERCISE 5.2** </font>

In [ ]:
# Create a hyperparameter grid for Random Forest


# Create a hyperparameter grid for Gradient Booster

**Lesson Workspace**

In [ ]:
# Create the hyperparameter_grids dictionary

In [ ]:
# Run the code below to make sure everything is set up correctly
for key in ['enet', 'gb', 'ridge', 'rf', 'lasso']:
    if key in hyperparameter_grids:
        if type(hyperparameter_grids[key]) is dict:
            print( key, 'was found, and it is a grid.' )
        else:
            print( key, 'was found, but it is not a grid.' )
    else:
        print( key, 'was not found')

### 6. Cross Validation

**Lesson Workspace**

In [ ]:
# Import GridSearchCV

<font color = 'blue'> **EXERCISE 6.1** </font>

<font color = 'blue'> **EXERCISE 6.2** </font>

### 7. Selecting a Winning Model

**Lesson Workspace**

In [ ]:
# Import the r-squared and mean absolute error metrics

<font color = 'blue'> **EXERCISE 7.1** </font>

<font color = 'blue'> **EXERCISE 7.2** </font>

In [ ]:
# Make prediction with test data


# Plot predictions on x axis and actuals on y axis


# Label axes and show graph